# Generated by Django 5.1.1 on 2024-10-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_brand_remove_products_images_images_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='weight',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adminapp.products')),
            ],
            options={
                'unique_together': {('product', 'weight')},
            },
        ),
    ]
