# Generated by Django 5.1.1 on 2024-10-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_products_weight_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
