# Generated by Django 5.1.1 on 2024-10-19 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
    ]
