# Generated by Django 5.1.1 on 2024-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='euphouser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='euphouser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
