# Generated by Django 5.1.1 on 2024-11-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_euphouser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euphouser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
