# Generated by Django 5.1.1 on 2024-11-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_alter_order_payment_method'),
        ('adminapp', '0027_rename_payment_method_order_paymentmethod'),
    ]

    operations = [
    ]
