# Generated by Django 5.1.1 on 2024-11-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_merge_20241107_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='paymentmethod',
        ),
    ]
