# Generated by Django 5.1.1 on 2024-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
